### ISSUE TITLE
Extednd for generic usage

### ISSUE THREAD

**Issue by caco3** [soxfox42/typit#1]
Dear @soxfox42 

I like your clean code and nice stylesheet!
I will go and use it for a German variant of WORDLE.

I will send you some non-breakable Pull Requests. You can use them, else I keep them in my fork.

**Comment by soxfox42** [comment]
Hi @caco3, glad you like it :)

Happy for you to make a German version, just make sure you keep the license text in your project as required by the MIT license. You'll also want to change or remove the Google Analytics code, as it is linked to my GA4 property.

I'm going to close this issue, and I'll look at any PRs you send through.
